### PR TITLE
#48 Nested classes support

### PR DESCRIPTION
**Pull request by jmarcgit**
See #48

### CODE REVIEW

**Comment by jmarcgit** [comment]
I created a new pull with a single commit. Don't know where to start with JUnit...

**Comment by jmarcgit** [comment]
Hi, maybe there  is a better option to implement the enhancement. We could subclass the ClassPool to get all the instrumented classes (modified) so we could then save all of them. This would work for any additional class updated or generated during the process. What do you prefer ?

**Comment by barthel** [comment]
@jmarcgit Thanks for this PR.

I'll start to merge this simple solution. 
The JUnit test base is to small, I know. I'll add a test for you before I push the merged code.

Btw: Add a contributor entry with your datas in the POM file, if you like or I can do it for you too.

**Comment by barthel** [comment]
@jmarcgit I've merged this PR into the master branch.
I had to adjust the patch a bit and I added tests for it.

Please take a look at: 02ba5ab673ef34caa2584ac3b720efa8f15a1cbc.

Feel free to open a new PR to add a ``contributor`` entry in the POM file like:
https://github.com/icon-Systemhaus-GmbH/javassist-maven-plugin/blob/master/pom.xml#L45

**Pull request closed without merging**
